### ISSUE TITLE
Looking for Windows and Linux-Ubuntu solution

### ISSUE THREAD

**Issue by changkun** [miguelmota/terminal-tab#1]
Thanks for your excellent code.

I'm building a cross platform app and I would like to open the terminal cross all platform(`cmd` for Win, `bash` for Linux). I check your code it seems implemented by AppleScript?

But, is there any methodology to open `cmd` or `bash` GUI window through normal NodeJS? How can I implemented it? Any Ideas?

**Comment by miguelmota** [comment]
On windows command prompt I believe you just execute `cmd` on the prompt to open a new window, I don't if there is tab support since I'm not on windows. On Linux gnome terminal you can do `gnome-terminal --tab -e "command1"` to trigger a new tab. There are many different flavors of terminal on Linux so that will get tricky since you'd have to figure out which terminal they're on and trigger the new tab shortcut on that.
